const courseData = [
  {
    id: 1,
    category: "Career & Industry",
    title: "Careers in Cyber",
    description:
      "Discover diverse cybersecurity careers, essential skills, and industry opportunities today.",
    topics: [
      "Overview of Cyber Careers",
      "Educational Paths",
      "Industry Certifications",
      "Job Market Trends",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/CareersInCyber/landing.jpg"),
    state: "pending",
    link: "/CareersInCyber",
    favorite: false,
    myCourses: false,
  },
  {
    id: 2,
    category: "Tools & Techniques",
    title: "Burp Suite",
    description:
      "Master Burp Suite fundamentals, empowering cybersecurity testing and vulnerability assessment.",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
    state: "published",
    link: "/Burp_Suit",
    favorite: false,
    myCourses: false,
  },
  {
    id: 3,
    category: "Fundamentals",
    title: "Cookies",
    description:
      "Understand cookies’ roles, security implications, storage methods, and manipulation techniques.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/cookies/Cookies_transparent.png"),
    state: "published",
    link: "/cookies",
    favorite: false,
    myCourses: false,
  },
  {
    id: 4,
    category: "Vulnerabilities",
    title: "SQL Injection",
    description:
      "Identify SQL injection flaws, extract hidden data, and secure applications.",
    topics: [
      "Retrieving hidden data",
      "SQL injection UNION attacks",
      "Finding columns with a useful data type",
      "Using a SQL injection UNION attack to retrieve interesting data",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/SQL_Injection/landing3.png"),
    state: "published",
    link: "/sql_Injection",
    favorite: false,
    myCourses: false,
  },
  {
    id: 5,
    category: "Vulnerabilities",
    title: "Unrestricted File Upload",
    description:
      "Explore file upload risks, techniques, and methods to safeguard applications.",
    topics: [
      "What is Unrestricted File Upload?",
      "Why is it Dangerous?",
      "Attack Techniques",
      "Exploitation Scenarios",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Unrestricted File Upload/card_image.png"),
    state: "published",
    link: "/UnrestrictedFileUpload",
    favorite: false,
    myCourses: false,
  },
  {
    id: 6,
    category: "Fundamentals",
    title: "Linux Fundamentals",
    description:
      "Build essential Linux skills, mastering commands, filesystem navigation and operations.",
    topics: [
      "Running Your First Few Commands",
      "Interacting with the Filesystem",
      "Searching for Files",
      "Introduction to Shell Operators",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/linux/card_image.png"),
    state: "published",
    link: "/linux",
    favorite: false,
    myCourses: false,
  },
  {
    id: 7,
    category: "Vulnerabilities",
    title: "Access Control Vulnerabilities",
    description:
      "Learn to detect and mitigate access control vulnerabilities in applications.",
    topics: [
      "What are Access Control Vulnerabilities?",
      "Types of Access Control Flaws",
      "Exploitation Examples",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/ACV/Landing.jpg"),
    state: "published",
    link: "/AC_Vuln",
    favorite: false,
    myCourses: false,
  },
  {
    id: 8,
    category: "Vulnerabilities",
    title: "Broken Authentication",
    description:
      "Secure authentication mechanisms to prevent account takeovers and data breaches.",
    topics: [
      "Weak Passwords",
      "Session Management Issues",
      "Lack of MFA",
      "Credential Stuffing",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Broken Authentication/card_image.png"),
    state: "published",
    link: "/broken-auth",
    favorite: false,
    myCourses: false,
  },
  {
    id: 9,
    category: "Fundamentals",
    title: "Bash Scripting",
    description:
      "Develop efficient Bash scripts to automate tasks and system management.",
    topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
    difficulty: "Beginner",
    image: require("../../assets/img/bash/bash_course_logo.png"),
    state: "published",
    link: "/bash-scripting",
    favorite: false,
    myCourses: false,
  },
  {
    id: 10,
    category: "Vulnerabilities",
    title: "Business Logic Vulnerabilities",
    description:
      "Analyze business logic flaws, exploitation methods, and strategies for mitigation.",
    topics: [
      "Understanding Business Logic",
      "Identifying Flaws",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/BLV/Landing.jpg"),
    state: "published",
    link: "/BL_Vuln",
    favorite: false,
    myCourses: false,
  },
  {
    id: 11,
    category: "Vulnerabilities",
    title: "Insecure Direct Object Reference(IDOR)",
    description:
      "Explore IDOR vulnerabilities, unauthorized access, common examples, and mitigation strategies.",
    topics: [
      "What is IDOR?",
      "Why is it Dangerous?",
      "Common Examples.",
      "Exploitation Techniques.",
      "Mitigation Strategies.",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
    state: "published",
    link: "/Insecure_Direct_Object_Reference(IDOR)",
    favorite: false,
    myCourses: false,
  },
  {
    id: 12,
    category: "Tools & Techniques",
    title: "Obfuscation",
    description:
      "Learn code obfuscation techniques to protect intellectual property and security.",
    topics: [
      "What are Obfuscation & Deobfuscation?",
      "Why do we use Obfuscation?",
      "Javascript Obfuscation",
      "JS Deobfuscation Tools",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Obfuscation/card_image.png"),
    state: "published",
    link: "/obfuscation",
    favorite: false,
    myCourses: false,
  },
  {
    id: 13,
    category: "Vulnerabilities",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Understand CSRF attack vectors, mitigation techniques, and prevention best practices.",
    topics: [
      "Understanding CSRF",
      "Exploitation Methods",
      "Prevention Techniques",
      "Real-world Examples",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/CSRF/landing.jpg"),
    state: "published",
    link: "/CSRF",
    favorite: false,
    myCourses: false,
  },
  {
    id: 14,
    category: "Vulnerabilities",
    title: "Path Traversal",
    description:
      "Discover path traversal techniques and prevention measures for secure files.",
    topics: [
      "Path traversal techniques",
      "Directory traversal prevention",
      "Secure file access mechanisms",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
    state: "published",
    link: "/Path__Traversal",
    favorite: false,
    myCourses: false,
  },
  {
    id: 15,
    category: "Fundamentals",
    title: "Cryptography",
    description:
      "Master cryptography principles, encryption types, and techniques for secure communications.",
    topics: [
      "What is Cryptography?",
      "What is Steganography?",
      "How does Steganography differ from Cryptography?",
      "Types of Encryption",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Cryptography/card_image.png"),
    state: "published",
    link: "/cryptography",
    favorite: false,
    myCourses: false,
  },
  {
    id: 16,
    category: "Fundamentals",
    title: "Regular expressions",
    description:
      "Craft effective regular expressions for text matching, searching, and parsing.",
    topics: [
      "Basics of Regex",
      "Character Classes",
      "Quantifiers and Grouping",
      "Practical Examples",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Regex/Landing.jpg"),
    state: "published",
    link: "/Regex",
    favorite: false,
    myCourses: false,
  },
  {
    id: 17,
    category: "Vulnerabilities",
    title: "Cross-Site Scripting",
    description:
      "Identify and mitigate cross-site scripting risks in modern web applications.",
    topics: [
      "What is Cross-Site Scripting?",
      "Types of XSS",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
    state: "published",
    link: "/xss",
    favorite: false,
    myCourses: false,
  },
  {
    id: 18,
    category: "Tools & Techniques",
    title: "wireshark",
    description:
      "Utilize Wireshark for deep network traffic analysis and security monitoring.",
    topics: [
      "Wireshark Overview",
      "Collection Methods",
      "ARP Traffic",
      "ICMP & TCP Traffic",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/wireshark/card_image.png"),
    state: "published",
    link: "/wireshark",
    favorite: false,
    myCourses: false,
  },
  {
    id: 19,
    category: "Fundamentals",
    title: "Hashing",
    description:
      "Understand hashing concepts, algorithms, security implications, and best practices thoroughly.",
    topics: [
      "Introduction to Hashing",
      "Common Hashing Algorithms",
      "Security Implications",
      "Best Practices",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Hashing/landing.jpg"),
    state: "published",
    link: "/Hashing",
    favorite: false,
    myCourses: false,
  },
  {
    id: 20,
    category: "Vulnerabilities",
    title: "Command Injection",
    description:
      "Learn command injection techniques, exploitation risks, and secure coding practices.",
    topics: [
      "Understanding Command Injection",
      "Networking Weaknesses",
      "Common Web Attacks",
      "Using the Linux OS",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Command Injection/Content_Command_Injection.jpg"),
    state: "published",
    link: "/Command_Injection",
    favorite: false,
    myCourses: false,
  },
  {
    id: 21,
    category: "Vulnerabilities",
    title: "File Inclusion",
    description:
      "Examine file inclusion flaws, exploit methods, and robust remediation strategies.",
    topics: [
      "Path Traversal",
      "Local File Inclusion (LFI)",
      "Remote File Inclusion (RFI)",
      "Remediation",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/File Inclusion/card_image.png"),
    state: "published",
    link: "/fileinclusion",
    favorite: false,
    myCourses: false,
  },
  {
    id: 22,
    category: "Fundamentals",
    title: "Digital Forensics",
    description:
      "Investigate digital evidence using forensic techniques for accurate cyber investigations.",
    topics: [
      "Introduction to Digital Forensics",
      "Evidence Collection",
      "Analysis Techniques",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/AudFor/landing.png"),
    state: "published",
    link: "/Digital_Forensics",
    favorite: false,
    myCourses: false,
  },
  {
    id: 23,
    category: "Vulnerabilities",
    title: "Insecure Deserialization",
    description:
      "Detect insecure deserialization risks, prevent code execution, and secure data.",
    topics: [
      "Serialization and Deserialization",
      "Remote Code Execution (RCE)",
      "Data Tampering Techniques",
      "Preventing Insecure Deserialization",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
    state: "published",
    link: "/Insecure_Deserialization",
    favorite: false,
    myCourses: false,
  },
  {
    id: 24,
    category: "Vulnerabilities",
    title: "Server Side Template Injection (SSTI)",
    description:
      "Understand SSTI risks, exploit techniques, and prevention strategies for templates.",
    topics: [
      "Introduction",
      "SSTI Vulnerabilities",
      "Constructing a SSTI Attack",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Server Side Template Injection/card_image.png"),
    state: "coming-soon",
    // link: '/SSTI',
    link: "/coming-soon",
    favorite: false,
    myCourses: false,
  },
  {
    id: 25,
    category: "Tools & Techniques",
    title: "API Hacking & Testing",
    description:
      "Master API hacking techniques, testing methodologies, and security assessment procedures.",
    topics: [
      "API Fundamentals",
      "Common Vulnerabilities",
      "Testing Tools",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Api_Hacking/landing.png"),
    state: "published",
    link: "/Api_Hacking",

    favorite: false,
    myCourses: false,
  },
  {
    id: 26,
    category: "Fundamentals",
    title: "Race Condition",
    description:
      "A race condition occurs when multiple processes access shared resources simultaneously in an uncontrolled manner, leading to unexpected errors or security vulnerabilities.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Intermediate",
    image: require("../../assets/img/Condition_Race/Race Condition.png"),
    state: "published",
    link: "/Race_Condition",
    favorite: false,
    myCourses: false,
  },
  {
    id: 27,
    category: "Vulnerabilities",
    title: "Captcha Bypass",
    description:
      "Examine captcha bypass methods, security flaws, and advanced prevention techniques.",
    topics: [
      "Introduction to Captcha",
      "Bypass Techniques",
      "Real-world Examples",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Captcha Bypass/card_image.png"),
    state: "published",
    link: "/captchabypass",
    favorite: false,
    myCourses: false,
  },
  {
    id: 28,
    category: "Vulnerabilities",
    title: "click jacking",
    description:
      "Investigate click jacking strategies, analyze attack mechanisms, and implement countermeasures.",
    topics: [
      "What is Click Jacking?",
      "Attack Techniques",
      "Prevention Methods",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Click_Jacking/landing.jpg"),
    state: "published",
    link: "/Click_Jacking",
    favorite: false,
    myCourses: false,
  },
  {
    id: 29,
    category: "Fundamentals",
    title: "Server Side Request Forgery (SSRF)",
    description:
      "Placeholder course offering preliminary topics, soon updated with comprehensive content.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Hard",
    image: require("../../assets/img/Server Side Template Injection/Untitled.png"),
    state: "coming-soon",
    // link: '/ssrf',
    link: "/coming-soon",
    favorite: false,
    myCourses: false,
  },
  {
    id: 30,
    category: "Vulnerabilities",
    title: "JWT attacks",
    description:
      "Examine JWT attack vectors, token vulnerabilities, and secure handling methods.",
    topics: [
      "Introduction to JWT",
      "Common Attack Vectors",
      "Security Best Practices",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/JWT attacks/card_image.png"),
    state: "coming-soon",
    // link: '/jwtattacks',
    link: "/coming-soon",
    favorite: false,
    myCourses: false,
  },
  {
    id: 31,
    category: "Fav Topics",
    title: "Regular expressions",
    description:
      "Craft effective regular expressions for text matching, searching, and parsing.",
    topics: [
      "Basics of Regex",
      "Character Classes",
      "Quantifiers and Grouping",
      "Practical Examples",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Regex/Landing.jpg"),
    state: "published",
    link: "/Regex",
    favorite: false,
    myCourses: false,
  },
  {
    id: 32,
    category: "My Courses",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Understand CSRF attack vectors, mitigation techniques, and prevention best practices.",
    topics: [
      "Understanding CSRF",
      "Exploitation Methods",
      "Prevention Techniques",
      "Real-world Examples",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/CSRF/landing.jpg"),
    state: "published",
    link: "/CSRF",
    favorite: false,
    myCourses: false,
  },
  {
    id: 33,
    category: "My Courses",
    title: "Burp Suite",
    description:
      "Master Burp Suite fundamentals, empowering cybersecurity testing and vulnerability assessment.",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
    state: "published",
    link: "/Burp_Suit",
    favorite: false,
    myCourses: false,
  },
  {
    id: 34,
    category: "My Courses",
    title: "Cookies",
    description:
      "Understand cookies’ roles, security implications, storage methods, and manipulation techniques.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/cookies/Cookies_transparent.png"),
    state: "published",
    link: "/cookies",
    favorite: false,
    myCourses: false,
  },
];

// ==== Two array en , ar ======

// const courseData = {
//   en: [
//     {
//       id: 1,
//       category: "Career & Industry",
//       title: "Careers in Cyber",
//       description:
//         "Discover diverse cybersecurity careers, essential skills, and industry opportunities today.",
//       topics: [
//         "Overview of Cyber Careers",
//         "Educational Paths",
//         "Industry Certifications",
//         "Job Market Trends",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/CareersInCyber/landing.jpg"),
//       state: "pending",
//       link: "/CareersInCyber",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 2,
//       category: "Tools & Techniques",
//       title: "Burp Suite",
//       description:
//         "Master Burp Suite fundamentals, empowering cybersecurity testing and vulnerability assessment.",
//       topics: [
//         "Learn about different careers in cyber",
//         "Hack your first application",
//         "Defend against a live cyber attack",
//         "Explore security topics in the industry",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
//       state: "published",
//       link: "/Burp_Suit",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 3,
//       category: "Fundamentals",
//       title: "Cookies",
//       description:
//         "Understand cookies' roles, security implications, storage methods, and manipulation techniques.",
//       topics: [
//         "What Are Cookies?",
//         "What are Cookies Used For?",
//         "Where are Cookies Stored?",
//         "Cookies Manipulation",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/cookies/Cookies_transparent.png"),
//       state: "published",
//       link: "/cookies",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 4,
//       category: "Vulnerabilities",
//       title: "SQL Injection",
//       description:
//         "Identify SQL injection flaws, extract hidden data, and secure applications.",
//       topics: [
//         "Retrieving hidden data",
//         "SQL injection UNION attacks",
//         "Finding columns with a useful data type",
//         "Using a SQL injection UNION attack to retrieve interesting data",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/SQL_Injection/landing3.png"),
//       state: "published",
//       link: "/sql_Injection",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 5,
//       category: "Vulnerabilities",
//       title: "Unrestricted File Upload",
//       description:
//         "Explore file upload risks, techniques, and methods to safeguard applications.",
//       topics: [
//         "What is Unrestricted File Upload?",
//         "Why is it Dangerous?",
//         "Attack Techniques",
//         "Exploitation Scenarios",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Unrestricted File Upload/card_image.png"),
//       state: "published",
//       link: "/UnrestrictedFileUpload",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 6,
//       category: "Fundamentals",
//       title: "Linux Fundamentals",
//       description:
//         "Build essential Linux skills, mastering commands, filesystem navigation and operations.",
//       topics: [
//         "Running Your First Few Commands",
//         "Interacting with the Filesystem",
//         "Searching for Files",
//         "Introduction to Shell Operators",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/linux/card_image.png"),
//       state: "published",
//       link: "/linux",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 7,
//       category: "Vulnerabilities",
//       title: "Access Control Vulnerabilities",
//       description:
//         "Learn to detect and mitigate access control vulnerabilities in applications.",
//       topics: [
//         "What are Access Control Vulnerabilities?",
//         "Types of Access Control Flaws",
//         "Exploitation Examples",
//         "Mitigation Techniques",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/ACV/Landing.jpg"),
//       state: "published",
//       link: "/AC_Vuln",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 8,
//       category: "Vulnerabilities",
//       title: "Broken Authentication",
//       description:
//         "Secure authentication mechanisms to prevent account takeovers and data breaches.",
//       topics: [
//         "Weak Passwords",
//         "Session Management Issues",
//         "Lack of MFA",
//         "Credential Stuffing",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Broken Authentication/card_image.png"),
//       state: "published",
//       link: "/broken-auth",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 9,
//       category: "Fundamentals",
//       title: "Bash Scripting",
//       description:
//         "Develop efficient Bash scripts to automate tasks and system management.",
//       topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
//       difficulty: "Beginner",
//       image: require("../../assets/img/bash/bash_course_logo.png"),
//       state: "published",
//       link: "/bash-scripting",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 10,
//       category: "Vulnerabilities",
//       title: "Business Logic Vulnerabilities",
//       description:
//         "Analyze business logic flaws, exploitation methods, and strategies for mitigation.",
//       topics: [
//         "Understanding Business Logic",
//         "Identifying Flaws",
//         "Exploitation Techniques",
//         "Mitigation Strategies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/BLV/Landing.jpg"),
//       state: "published",
//       link: "/BL_Vuln",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 11,
//       category: "Vulnerabilities",
//       title: "Insecure Direct Object Reference(IDOR)",
//       description:
//         "Explore IDOR vulnerabilities, unauthorized access, common examples, and mitigation strategies.",
//       topics: [
//         "What is IDOR?",
//         "Why is it Dangerous?",
//         "Common Examples.",
//         "Exploitation Techniques.",
//         "Mitigation Strategies.",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
//       state: "published",
//       link: "/Insecure_Direct_Object_Reference(IDOR)",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 12,
//       category: "Tools & Techniques",
//       title: "Obfuscation",
//       description:
//         "Learn code obfuscation techniques to protect intellectual property and security.",
//       topics: [
//         "What are Obfuscation & Deobfuscation?",
//         "Why do we use Obfuscation?",
//         "Javascript Obfuscation",
//         "JS Deobfuscation Tools",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/Obfuscation/card_image.png"),
//       state: "published",
//       link: "/obfuscation",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 13,
//       category: "Vulnerabilities",
//       title: "Cross Site Request Forgery (CSRF)",
//       description:
//         "Understand CSRF attack vectors, mitigation techniques, and prevention best practices.",
//       topics: [
//         "Understanding CSRF",
//         "Exploitation Methods",
//         "Prevention Techniques",
//         "Real-world Examples",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/CSRF/landing.jpg"),
//       state: "published",
//       link: "/CSRF",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 14,
//       category: "Vulnerabilities",
//       title: "Path Traversal",
//       description:
//         "Discover path traversal techniques and prevention measures for secure files.",
//       topics: [
//         "Path traversal techniques",
//         "Directory traversal prevention",
//         "Secure file access mechanisms",
//         "Case Studies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
//       state: "published",
//       link: "/Path__Traversal",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 15,
//       category: "Fundamentals",
//       title: "Cryptography",
//       description:
//         "Master cryptography principles, encryption types, and techniques for secure communications.",
//       topics: [
//         "What is Cryptography?",
//         "What is Steganography?",
//         "How does Steganography differ from Cryptography?",
//         "Types of Encryption",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Cryptography/card_image.png"),
//       state: "published",
//       link: "/cryptography",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 16,
//       category: "Fundamentals",
//       title: "Regular expressions",
//       description:
//         "Craft effective regular expressions for text matching, searching, and parsing.",
//       topics: [
//         "Basics of Regex",
//         "Character Classes",
//         "Quantifiers and Grouping",
//         "Practical Examples",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/Regex/Landing.jpg"),
//       state: "published",
//       link: "/Regex",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 17,
//       category: "Vulnerabilities",
//       title: "Cross-Site Scripting",
//       description:
//         "Identify and mitigate cross-site scripting risks in modern web applications.",
//       topics: [
//         "What is Cross-Site Scripting?",
//         "Types of XSS",
//         "Exploitation Techniques",
//         "Mitigation Strategies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
//       state: "published",
//       link: "/xss",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 18,
//       category: "Tools & Techniques",
//       title: "wireshark",
//       description:
//         "Utilize Wireshark for deep network traffic analysis and security monitoring.",
//       topics: [
//         "Wireshark Overview",
//         "Collection Methods",
//         "ARP Traffic",
//         "ICMP & TCP Traffic",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/wireshark/card_image.png"),
//       state: "published",
//       link: "/wireshark",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 19,
//       category: "Fundamentals",
//       title: "Hashing",
//       description:
//         "Understand hashing concepts, algorithms, security implications, and best practices thoroughly.",
//       topics: [
//         "Introduction to Hashing",
//         "Common Hashing Algorithms",
//         "Security Implications",
//         "Best Practices",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/Hashing/landing.jpg"),
//       state: "published",
//       link: "/Hashing",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 20,
//       category: "Vulnerabilities",
//       title: "Command Injection",
//       description:
//         "Learn command injection techniques, exploitation risks, and secure coding practices.",
//       topics: [
//         "Understanding Command Injection",
//         "Networking Weaknesses",
//         "Common Web Attacks",
//         "Using the Linux OS",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Command Injection/Content_Command_Injection.jpg"),
//       state: "published",
//       link: "/Command_Injection",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 21,
//       category: "Vulnerabilities",
//       title: "File Inclusion",
//       description:
//         "Examine file inclusion flaws, exploit methods, and robust remediation strategies.",
//       topics: [
//         "Path Traversal",
//         "Local File Inclusion (LFI)",
//         "Remote File Inclusion (RFI)",
//         "Remediation",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/File Inclusion/card_image.png"),
//       state: "published",
//       link: "/fileinclusion",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 22,
//       category: "Fundamentals",
//       title: "Digital Forensics",
//       description:
//         "Investigate digital evidence using forensic techniques for accurate cyber investigations.",
//       topics: [
//         "Introduction to Digital Forensics",
//         "Evidence Collection",
//         "Analysis Techniques",
//         "Case Studies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/AudFor/landing.png"),
//       state: "published",
//       link: "/Digital_Forensics",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 23,
//       category: "Vulnerabilities",
//       title: "Insecure Deserialization",
//       description:
//         "Detect insecure deserialization risks, prevent code execution, and secure data.",
//       topics: [
//         "Serialization and Deserialization",
//         "Remote Code Execution (RCE)",
//         "Data Tampering Techniques",
//         "Preventing Insecure Deserialization",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
//       state: "published",
//       link: "/Insecure_Deserialization",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 24,
//       category: "Vulnerabilities",
//       title: "Server Side Template Injection (SSTI)",
//       description:
//         "Understand SSTI risks, exploit techniques, and prevention strategies for templates.",
//       topics: [
//         "Introduction",
//         "SSTI Vulnerabilities",
//         "Constructing a SSTI Attack",
//         "Prevention Strategies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Server Side Template Injection/card_image.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 25,
//       category: "Tools & Techniques",
//       title: "API Hacking & Testing",
//       description:
//         "Master API hacking techniques, testing methodologies, and security assessment procedures.",
//       topics: [
//         "API Fundamentals",
//         "Common Vulnerabilities",
//         "Testing Tools",
//         "Mitigation Strategies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Api_Hacking/landing.png"),
//       state: "published",
//       link: "/Api_Hacking",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 26,
//       category: "Fundamentals",
//       title: "Race Condition",
//       description:
//         "A race condition occurs when multiple processes access shared resources simultaneously in an uncontrolled manner, leading to unexpected errors or security vulnerabilities.",
//       topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Condition_Race/Race Condition.png"),
//       state: "published",
//       link: "/Race_Condition",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 27,
//       category: "Vulnerabilities",
//       title: "Captcha Bypass",
//       description:
//         "Examine captcha bypass methods, security flaws, and advanced prevention techniques.",
//       topics: [
//         "Introduction to Captcha",
//         "Bypass Techniques",
//         "Real-world Examples",
//         "Prevention Strategies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Captcha Bypass/card_image.png"),
//       state: "published",
//       link: "/captchabypass",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 28,
//       category: "Vulnerabilities",
//       title: "click jacking",
//       description:
//         "Investigate click jacking strategies, analyze attack mechanisms, and implement countermeasures.",
//       topics: [
//         "What is Click Jacking?",
//         "Attack Techniques",
//         "Prevention Methods",
//         "Case Studies",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Click_Jacking/landing.jpg"),
//       state: "published",
//       link: "/Click_Jacking",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 29,
//       category: "Fundamentals",
//       title: "Server Side Request Forgery (SSRF)",
//       description:
//         "Placeholder course offering preliminary topics, soon updated with comprehensive content.",
//       topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
//       difficulty: "Hard",
//       image: require("../../assets/img/Server Side Template Injection/Untitled.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 30,
//       category: "Vulnerabilities",
//       title: "JWT attacks",
//       description:
//         "Examine JWT attack vectors, token vulnerabilities, and secure handling methods.",
//       topics: [
//         "Introduction to JWT",
//         "Common Attack Vectors",
//         "Security Best Practices",
//         "Mitigation Techniques",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/JWT attacks/card_image.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 31,
//       category: "Fav Topics",
//       title: "Regular expressions",
//       description:
//         "Craft effective regular expressions for text matching, searching, and parsing.",
//       topics: [
//         "Basics of Regex",
//         "Character Classes",
//         "Quantifiers and Grouping",
//         "Practical Examples",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/Regex/Landing.jpg"),
//       state: "published",
//       link: "/Regex",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 32,
//       category: "My Courses",
//       title: "Cross Site Request Forgery (CSRF)",
//       description:
//         "Understand CSRF attack vectors, mitigation techniques, and prevention best practices.",
//       topics: [
//         "Understanding CSRF",
//         "Exploitation Methods",
//         "Prevention Techniques",
//         "Real-world Examples",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/CSRF/landing.jpg"),
//       state: "published",
//       link: "/CSRF",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 33,
//       category: "My Courses",
//       title: "Burp Suite",
//       description:
//         "Master Burp Suite fundamentals, empowering cybersecurity testing and vulnerability assessment.",
//       topics: [
//         "Learn about different careers in cyber",
//         "Hack your first application",
//         "Defend against a live cyber attack",
//         "Explore security topics in the industry",
//       ],
//       difficulty: "Intermediate",
//       image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
//       state: "published",
//       link: "/Burp_Suit",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 34,
//       category: "My Courses",
//       title: "Cookies",
//       description:
//         "Understand cookies' roles, security implications, storage methods, and manipulation techniques.",
//       topics: [
//         "What Are Cookies?",
//         "What are Cookies Used For?",
//         "Where are Cookies Stored?",
//         "Cookies Manipulation",
//       ],
//       difficulty: "Beginner",
//       image: require("../../assets/img/cookies/Cookies_transparent.png"),
//       state: "published",
//       link: "/cookies",
//       favorite: false,
//       myCourses: false,
//     },
//   ],
//   ar: [
//     {
//       id: 1,
//       category: "المسار الوظيفي والصناعة",
//       title: "الوظائف في الأمن السيبراني",
//       description:
//         "اكتشف الوظائف المتنوعة في الأمن السيبراني، المهارات الأساسية، والفرص المتاحة في الصناعة اليوم.",
//       topics: [
//         "نظرة عامة على الوظائف في الأمن السيبراني",
//         "المسارات التعليمية",
//         "الشهادات المهنية في الصناعة",
//         "اتجاهات سوق العمل",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/CareersInCyber/landing.jpg"),
//       state: "pending",
//       link: "/CareersInCyber",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 2,
//       category: "الأدوات والتقنيات",
//       title: "برب سويت",
//       description:
//         "أتقن أساسيات برب سويت، لتعزيز اختبارات الأمن السيبراني وتقييم الثغرات الأمنية.",
//       topics: [
//         "تعرف على الوظائف المختلفة في الأمن السيبراني",
//         "اخترق أول تطبيق لك",
//         "دافع ضد هجوم سيبراني مباشر",
//         "استكشف مواضيع الأمان في الصناعة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
//       state: "published",
//       link: "/Burp_Suit",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 3,
//       category: "الأساسيات",
//       title: "الكوكيز",
//       description:
//         "افهم دور الكوكيز، الآثار الأمنية، طرق التخزين، وتقنيات التلاعب بها.",
//       topics: [
//         "ما هي الكوكيز؟",
//         "ما استخدامات الكوكيز؟",
//         "أين يتم تخزين الكوكيز؟",
//         "التلاعب بالكوكيز",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/cookies/Cookies_transparent.png"),
//       state: "published",
//       link: "/cookies",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 4,
//       category: "الثغرات الأمنية",
//       title: "حقن SQL",
//       description:
//         "تعرف على ثغرات حقن SQL، استخراج البيانات المخفية، وتأمين التطبيقات.",
//       topics: [
//         "استرجاع البيانات المخفية",
//         "هجمات الاتحاد في حقن SQL",
//         "إيجاد الأعمدة بنوع بيانات مفيد",
//         "استخدام هجوم الاتحاد في حقن SQL لاسترجاع بيانات مهمة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/SQL_Injection/landing3.png"),
//       state: "published",
//       link: "/sql_Injection",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 5,
//       category: "الثغرات الأمنية",
//       title: "رفع الملفات غير المقيد",
//       description:
//         "استكشف مخاطر رفع الملفات، التقنيات، والطرق لحماية التطبيقات.",
//       topics: [
//         "ما هو رفع الملفات غير المقيد؟",
//         "لماذا هو خطير؟",
//         "تقنيات الهجوم",
//         "سيناريوهات الاستغلال",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Unrestricted File Upload/card_image.png"),
//       state: "published",
//       link: "/UnrestrictedFileUpload",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 6,
//       category: "الأساسيات",
//       title: "أساسيات لينكس",
//       description:
//         "ابنِ مهارات لينكس الأساسية، أتقن الأوامر، التنقل في نظام الملفات، والعمليات.",
//       topics: [
//         "تشغيل أوامرك الأولى",
//         "التفاعل مع نظام الملفات",
//         "البحث عن الملفات",
//         "مقدمة لمشغلي الشل",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/linux/card_image.png"),
//       state: "published",
//       link: "/linux",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 7,
//       category: "الثغرات الأمنية",
//       title: "ثغرات التحكم في الوصول",
//       description: "تعلم اكتشاف وتخفيف ثغرات التحكم في الوصول في التطبيقات.",
//       topics: [
//         "ما هي ثغرات التحكم في الوصول؟",
//         "أنواع عيوب التحكم في الوصول",
//         "أمثلة على الاستغلال",
//         "تقنيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/ACV/Landing.jpg"),
//       state: "published",
//       link: "/AC_Vuln",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 8,
//       category: "الثغرات الأمنية",
//       title: "المصادقة المعطلة",
//       description:
//         "أمن آليات المصادقة لمنع الاستيلاء على الحسابات وخرق البيانات.",
//       topics: [
//         "كلمات المرور الضعيفة",
//         "مشاكل إدارة الجلسات",
//         "عدم وجود المصادقة متعددة العوامل",
//         "حشو بيانات الاعتماد",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Broken Authentication/card_image.png"),
//       state: "published",
//       link: "/broken-auth",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 9,
//       category: "الأساسيات",
//       title: "برمجة باش",
//       description: "طور نصوص باش فعالة لأتمتة المهام وإدارة النظام.",
//       topics: ["نصوص باش بسيطة", "المتغيرات", "المعاملات", "المصفوفات"],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/bash/bash_course_logo.png"),
//       state: "published",
//       link: "/bash-scripting",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 10,
//       category: "الثغرات الأمنية",
//       title: "ثغرات المنطق التجاري",
//       description:
//         "حلل عيوب المنطق التجاري، طرق الاستغلال، واستراتيجيات التخفيف.",
//       topics: [
//         "فهم المنطق التجاري",
//         "تحديد العيوب",
//         "تقنيات الاستغلال",
//         "استراتيجيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/BLV/Landing.jpg"),
//       state: "published",
//       link: "/BL_Vuln",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 11,
//       category: "الثغرات الأمنية",
//       title: "الإشارة المباشرة غير الآمنة للكائنات (IDOR)",
//       description:
//         "استكشف ثغرات IDOR، الوصول غير المصرح به، الأمثلة الشائعة، واستراتيجيات التخفيف.",
//       topics: [
//         "ما هو IDOR؟",
//         "لماذا هو خطير؟",
//         "أمثلة شائعة",
//         "تقنيات الاستغلال",
//         "استراتيجيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
//       state: "published",
//       link: "/Insecure_Direct_Object_Reference(IDOR)",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 12,
//       category: "الأدوات والتقنيات",
//       title: "التعتيم",
//       description: "تعلم تقنيات تعتيم الكود لحماية الملكية الفكرية والأمان.",
//       topics: [
//         "ما هي عملية التعتيب وإزالة التعتيب؟",
//         "لماذا نستخدم التعتيب؟",
//         "تعتيم جافا سكريبت",
//         "أدوات إزالة تعتيم JS",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/Obfuscation/card_image.png"),
//       state: "published",
//       link: "/obfuscation",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 13,
//       category: "الثغرات الأمنية",
//       title: "تزوير الطلب عبر المواقع (CSRF)",
//       description:
//         "افهم نواقل هجوم CSRF، تقنيات التخفيف، وأفضل ممارسات الوقاية.",
//       topics: [
//         "فهم CSRF",
//         "طرق الاستغلال",
//         "تقنيات الوقاية",
//         "أمثلة من العالم الحقيقي",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/CSRF/landing.jpg"),
//       state: "published",
//       link: "/CSRF",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 14,
//       category: "الثغرات الأمنية",
//       title: "اختراق المسار",
//       description:
//         "اكتشف تقنيات اختراق المسار وإجراءات الوقاية للملفات الآمنة.",
//       topics: [
//         "تقنيات اختراق المسار",
//         "منع اختراق الدلائل",
//         "آليات الوصول الآمن للملفات",
//         "دراسات حالة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
//       state: "published",
//       link: "/Path__Traversal",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 15,
//       category: "الأساسيات",
//       title: "التشفير",
//       description:
//         "أتقن مبادئ التشفير، أنواع التشفير، والتقنيات للاتصالات الآمنة.",
//       topics: [
//         "ما هو التشفير؟",
//         "ما هو إخفاء المعلومات؟",
//         "كيف يختلف إخفاء المعلومات عن التشفير؟",
//         "أنواع التشفير",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Cryptography/card_image.png"),
//       state: "published",
//       link: "/cryptography",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 16,
//       category: "الأساسيات",
//       title: "التعبيرات النمطية",
//       description: "اصنع تعبيرات نمطية فعالة لمطابقة النص، البحث، والتحليل.",
//       topics: [
//         "أساسيات التعبيرات النمطية",
//         "فئات الأحرف",
//         "المحددات والتجميع",
//         "أمثلة عملية",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/Regex/Landing.jpg"),
//       state: "published",
//       link: "/Regex",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 17,
//       category: "الثغرات الأمنية",
//       title: "اختراق المواقع عبر النصوص (XSS)",
//       description: "حدد مخاطر XSS وخففها في تطبيقات الويب الحديثة.",
//       topics: [
//         "ما هو اختراق المواقع عبر النصوص؟",
//         "أنواع XSS",
//         "تقنيات الاستغلال",
//         "استراتيجيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
//       state: "published",
//       link: "/xss",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 18,
//       category: "الأدوات والتقنيات",
//       title: "واير شارك",
//       description:
//         "استخدم واير شارك لتحليل حركة المرور العميقة في الشبكة ومراقبة الأمان.",
//       topics: [
//         "نظرة عامة على واير شارك",
//         "طرق الجمع",
//         "حركة ARP",
//         "حركة ICMP و TCP",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/wireshark/card_image.png"),
//       state: "published",
//       link: "/wireshark",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 19,
//       category: "الأساسيات",
//       title: "التجزئة",
//       description:
//         "افهم مفاهيم التجزئة، الخوارزميات، الآثار الأمنية، وأفضل الممارسات بشكل شامل.",
//       topics: [
//         "مقدمة في التجزئة",
//         "خوارزميات التجزئة الشائعة",
//         "الآثار الأمنية",
//         "أفضل الممارسات",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/Hashing/landing.jpg"),
//       state: "published",
//       link: "/Hashing",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 20,
//       category: "الثغرات الأمنية",
//       title: "حقن الأوامر",
//       description:
//         "تعلم تقنيات حقن الأوامر، مخاطر الاستغلال، وممارسات البرمجة الآمنة.",
//       topics: [
//         "فهم حقن الأوامر",
//         "نقاط الضعف في الشبكات",
//         "هجمات الويب الشائعة",
//         "استخدام نظام لينكس",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Command Injection/Content_Command_Injection.jpg"),
//       state: "published",
//       link: "/Command_Injection",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 21,
//       category: "الثغرات",
//       title: "File Inclusion",
//       description:
//         "استكشاف ثغرات تضمين الملفات، طرق الاستغلال، وأقوى أساليب الحماية.",
//       topics: [
//         "Path Traversal",
//         "تضمين الملفات المحلي (LFI)",
//         "تضمين الملفات عن بُعد (RFI)",
//         "طرق المعالجة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/File Inclusion/card_image.png"),
//       state: "published",
//       link: "/fileinclusion",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 22,
//       category: "الأساسيات",
//       title: "التحقيقات الرقمية (Digital Forensics)",
//       description:
//         "تحليل الأدلة الرقمية باستخدام تقنيات التحقيق الجنائي للوصول إلى نتائج دقيقة.",
//       topics: [
//         "مقدمة في التحقيقات الرقمية",
//         "جمع الأدلة",
//         "تقنيات التحليل",
//         "دراسات حالة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/AudFor/landing.png"),
//       state: "published",
//       link: "/Digital_Forensics",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 23,
//       category: "الثغرات",
//       title: "Insecure Deserialization",
//       description:
//         "كشف مخاطر فك التسلسل غير الآمن، ومنع تنفيذ الأكواد الضارة وتأمين البيانات.",
//       topics: [
//         "التسلسل وفك التسلسل",
//         "تنفيذ الأوامر عن بُعد (RCE)",
//         "تقنيات التلاعب بالبيانات",
//         "منع فك التسلسل غير الآمن",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
//       state: "published",
//       link: "/Insecure_Deserialization",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 24,
//       category: "الثغرات",
//       title: "Server Side Template Injection (SSTI)",
//       description:
//         "فهم مخاطر حقن القوالب، تقنيات الاستغلال، واستراتيجيات الحماية.",
//       topics: ["مقدمة", "ثغرات SSTI", "بناء هجوم SSTI", "أساليب الحماية"],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Server Side Template Injection/card_image.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 25,
//       category: "الأدوات والتقنيات",
//       title: "اختبار واختراق الـ API",
//       description:
//         "إتقان أساليب اختبار واختراق الـ API وتحليل الثغرات وتقنيات التخفيف.",
//       topics: [
//         "أساسيات الـ API",
//         "الثغرات الشائعة",
//         "أدوات الاختبار",
//         "استراتيجيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Api_Hacking/landing.png"),
//       state: "published",
//       link: "/Api_Hacking",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 26,
//       category: "الأساسيات",
//       title: "Race Condition",
//       description:
//         "تحدث حالة Race Condition عندما تصل عدة عمليات إلى نفس الموارد في نفس الوقت بشكل غير منضبط، مما يؤدي إلى أخطاء غير متوقعة وثغرات أمنية.",
//       topics: ["موضوع 1", "موضوع 2", "موضوع 3", "موضوع 4"],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Condition_Race/Race Condition.png"),
//       state: "published",
//       link: "/Race_Condition",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 27,
//       category: "الثغرات",
//       title: "Captcha Bypass",
//       description:
//         "تحليل طرق تخطي الكابتشا، الثغرات المحتملة، وأساليب الحماية المتقدمة.",
//       topics: [
//         "مقدمة عن الكابتشا",
//         "طرق التخطي",
//         "أمثلة واقعية",
//         "أساليب الحماية",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Captcha Bypass/card_image.png"),
//       state: "published",
//       link: "/captchabypass",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 28,
//       category: "الثغرات",
//       title: "Clickjacking",
//       description:
//         "استكشاف أساليب هجوم Clickjacking، تحليل آليات الهجوم، وطرق الحماية.",
//       topics: [
//         "ما هو Clickjacking؟",
//         "تقنيات الهجوم",
//         "طرق الحماية",
//         "دراسات حالة",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Click_Jacking/landing.jpg"),
//       state: "published",
//       link: "/Click_Jacking",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 29,
//       category: "الأساسيات",
//       title: "Server Side Request Forgery (SSRF)",
//       description: "محتوى مبدئي سيتم تحديثه لاحقًا ليشمل شرحًا شاملًا للثغرة.",
//       topics: ["موضوع 1", "موضوع 2", "موضوع 3", "موضوع 4"],
//       difficulty: "صعب",
//       image: require("../../assets/img/Server Side Template Injection/Untitled.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 30,
//       category: "الثغرات",
//       title: "هجمات JWT",
//       description:
//         "تحليل ثغرات JWT، طرق استغلال التوكن، وكيفية التعامل الآمن معه.",
//       topics: [
//         "مقدمة عن JWT",
//         "طرق الهجوم الشائعة",
//         "أفضل ممارسات الأمان",
//         "استراتيجيات التخفيف",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/JWT attacks/card_image.png"),
//       state: "coming-soon",
//       link: "/coming-soon",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 31,
//       category: "المفضلة",
//       title: "Regular Expressions",
//       description: "إنشاء تعبيرات منتظمة فعّالة للبحث ومعالجة النصوص.",
//       topics: [
//         "أساسيات Regex",
//         "Character Classes",
//         "المجاميع والتكرار",
//         "أمثلة عملية",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/Regex/Landing.jpg"),
//       state: "published",
//       link: "/Regex",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 32,
//       category: "كورساتي",
//       title: "CSRF",
//       description: "فهم هجمات CSRF، أساليب الاستغلال، وطرق الحماية.",
//       topics: ["فهم CSRF", "طرق الاستغلال", "أساليب الحماية", "أمثلة واقعية"],
//       difficulty: "متوسط",
//       image: require("../../assets/img/CSRF/landing.jpg"),
//       state: "published",
//       link: "/CSRF",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 33,
//       category: "كورساتي",
//       title: "Burp Suite",
//       description:
//         "اتقان أساسيات Burp Suite لتعزيز اختبار الثغرات وتقييم الأمان.",
//       topics: [
//         "تعرف على الوظائف المختلفة",
//         "اختراق أول تطبيق",
//         "الدفاع ضد هجوم مباشر",
//         "استكشاف موضوعات الأمن",
//       ],
//       difficulty: "متوسط",
//       image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
//       state: "published",
//       link: "/Burp_Suit",
//       favorite: false,
//       myCourses: false,
//     },
//     {
//       id: 34,
//       category: "كورساتي",
//       title: "Cookies",
//       description:
//         "فهم دور الكوكيز، مخاطر الأمان، طرق التخزين، وتقنيات التلاعب.",
//       topics: [
//         "ما هي الكوكيز؟",
//         "استخدامات الكوكيز",
//         "أماكن تخزين الكوكيز",
//         "التلاعب بالكوكيز",
//       ],
//       difficulty: "مبتدئ",
//       image: require("../../assets/img/cookies/Cookies_transparent.png"),
//       state: "published",
//       link: "/cookies",
//       favorite: false,
//       myCourses: false,
//     },
//   ],
// };

export default courseData;
