const MCQCards = [
  {
    id: 1,
    en_title: 'MCQ on Blockchain & Cryptocurrency',
    ar_title: 'أسئلة اختيار من متعدد عن البلوكشين والعملات الرقمية',
    en_brief:
      'These are multiple choice questions that are designed to be a review for the exam.',
    ar_brief: 'هذه أسئلة اختيار من متعدد مصممة لتكون مراجعة للامتحان.',
    en_difficulty: 'Easy',
    ar_difficulty: 'سهل',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/BlockChain',
    isFree: true,
    topicsCount: 10,
  },
  {
    id: 2,
    en_title: 'MCQ on Computer Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للحاسوب',
    en_brief:
      'Test your knowledge of computer forensics with these review questions.',
    ar_brief: 'اختبر معرفتك بالطب الشرعي للحاسوب مع أسئلة المراجعة هذه.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Computer',
    isFree: true,
    topicsCount: 12,
  },
  {
    id: 3,
    en_title: 'MCQ on Cloud Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي السحابي',
    en_brief:
      'Prepare for cloud forensics challenges with this set of questions.',
    ar_brief: 'استعد لتحديات الطب الشرعي السحابي مع مجموعة الأسئلة هذه.',
    en_difficulty: 'Hard',
    ar_difficulty: 'صعب',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Cloud',
    isFree: true,
    topicsCount: 15,
  },
  {
    id: 4,
    en_title: 'MCQ on Database Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي لقواعد البيانات',
    en_brief:
      'Enhance your knowledge of database forensics with these targeted questions.',
    ar_brief:
      'عزز معرفتك بالطب الشرعي لقواعد البيانات مع هذه الأسئلة المستهدفة.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Database',
    isFree: true,
    topicsCount: 11,
  },
  {
    id: 5,
    en_title: 'MCQ on Data Recovery Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي لاستعادة البيانات',
    en_brief:
      'These questions cover data recovery techniques and their forensic applications.',
    ar_brief: 'تغطي هذه الأسئلة تقنيات استعادة البيانات وتطبيقاتها الشرعية.',
    en_difficulty: 'Easy',
    ar_difficulty: 'سهل',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/DataRecovery',
    isFree: true,
    topicsCount: 8,
  },
  {
    id: 6,
    en_title: 'MCQ on Drone Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للطائرات بدون طيار',
    en_brief:
      'Learn about drone forensics through these specialized questions.',
    ar_brief:
      'تعلم عن الطب الشرعي للطائرات بدون طيار من خلال هذه الأسئلة المتخصصة.',
    en_difficulty: 'Hard',
    ar_difficulty: 'صعب',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Drone',
    isFree: true,
    topicsCount: 14,
  },
  {
    id: 7,
    en_title: 'MCQ on Email Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للبريد الإلكتروني',
    en_brief: 'Understand email forensics with this set of review questions.',
    ar_brief:
      'افهم الطب الشرعي للبريد الإلكتروني مع مجموعة أسئلة المراجعة هذه.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Email',
    isFree: true,
    topicsCount: 10,
  },
  {
    id: 8,
    en_title: 'MCQ on Gaming Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للألعاب',
    en_brief:
      'Test your knowledge of gaming forensics with these unique questions.',
    ar_brief: 'اختبر معرفتك بالطب الشرعي للألعاب مع هذه الأسئلة الفريدة.',
    en_difficulty: 'Easy',
    ar_difficulty: 'سهل',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Gaming',
    isFree: true,
    topicsCount: 9,
  },
  {
    id: 9,
    en_title: 'MCQ on IoT Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي لإنترنت الأشياء',
    en_brief: 'Explore IoT forensics with these challenging questions.',
    ar_brief: 'استكشف الطب الشرعي لإنترنت الأشياء مع هذه الأسئلة الصعبة.',
    en_difficulty: 'Hard',
    ar_difficulty: 'صعب',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Iot',
    isFree: true,
    topicsCount: 13,
  },
  {
    id: 10,
    en_title: 'MCQ on Malware Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للبرمجيات الخبيثة',
    en_brief:
      'Prepare for malware forensics scenarios with these multiple-choice questions.',
    ar_brief:
      'استعد لسيناريوهات الطب الشرعي للبرمجيات الخبيثة مع أسئلة الاختيار من متعدد هذه.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Malware',
    isFree: true,
    topicsCount: 11,
  },
  {
    id: 11,
    en_title: 'MCQ on Mobile Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للهواتف المحمولة',
    en_brief:
      'Get ready for mobile forensics challenges with these targeted questions.',
    ar_brief:
      'استعد لتحديات الطب الشرعي للهواتف المحمولة مع هذه الأسئلة المستهدفة.',
    en_difficulty: 'Easy',
    ar_difficulty: 'سهل',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Mobile',
    isFree: true,
    topicsCount: 10,
  },
  {
    id: 12,
    en_title: 'MCQ on Multimedia Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للوسائط المتعددة',
    en_brief:
      'Dive into multimedia forensics with these specialized questions.',
    ar_brief: 'انغمس في الطب الشرعي للوسائط المتعددة مع هذه الأسئلة المتخصصة.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Multimedia',
    isFree: true,
    topicsCount: 12,
  },
  {
    id: 13,
    en_title: 'MCQ on Network Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للشبكات',
    en_brief: 'Understand network forensics through these detailed questions.',
    ar_brief: 'افهم الطب الشرعي للشبكات من خلال هذه الأسئلة التفصيلية.',
    en_difficulty: 'Hard',
    ar_difficulty: 'صعب',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Network',
    isFree: true,
    topicsCount: 15,
  },
  {
    id: 14,
    en_title: 'MCQ on Social Media Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي لوسائل التواصل الاجتماعي',
    en_brief: 'Learn about social media forensics with this set of questions.',
    ar_brief:
      'تعلم عن الطب الشرعي لوسائل التواصل الاجتماعي مع مجموعة الأسئلة هذه.',
    en_difficulty: 'Easy',
    ar_difficulty: 'سهل',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/SocialMedia',
    isFree: true,
    topicsCount: 9,
  },
  {
    id: 15,
    en_title: 'MCQ on Vehicle Forensics',
    ar_title: 'أسئلة اختيار من متعدد عن الطب الشرعي للمركبات',
    en_brief: 'Prepare for vehicle forensics with these insightful questions.',
    ar_brief: 'استعد للطب الشرعي للمركبات مع هذه الأسئلة الثاقبة.',
    en_difficulty: 'Medium',
    ar_difficulty: 'متوسط',
    image: require('../../assets/img/DigitalForensics/Email.jpg'),
    link: '/Digital_Forensics/MCQ/Vehicle',
    isFree: true,
    topicsCount: 11,
  },
];

export default MCQCards;
